services:
  - type: web
    name: visionx-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: JWT_SECRET
        value: "replace-with-a-strong-secret"